# -*- coding: utf-8 -*-
"""Exercicios aula 23/09 prova revisão.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xi03P640YE0M6eKFwlw1B1xRFs7RPOWq
"""

import numpy as np
# 1. Definir o Ponto P (-2, 4, 1, 1)
# Em computação gráfica, usamos vetores coluna para multiplicação de matrizes
P = np.array( [ [-2],
                [ 4],
                [ 1],
                [ 1] ] )
# 2. Definir os fatores de translação tx, ty, tz = 5, 2, 3
# 3. Montar a Matriz de Translação 4x4 (Mt)
# Iniciamos com uma matriz identidade e preenchemos a quarta coluna
Mt = np.array( [ [1, 0, 0, 5],
                 [0, 1, 0, 2],
                 [0, 0, 1, 3],
                 [0, 0, 0,  1] ] )
# 4. Realizar o cálculo: P' = Mt * P
P_linha = np.dot(Mt, P)
linhas_P_linha, colunas_P_linha = P_linha.shape

# pegar linha e coluna
linhas_Mt, colunas_Mt = Mt.shape
print("linha x coluna Mt", linhas_Mt, colunas_Mt)



# --- Exibição dos resultados no terminal --- print("Matriz de Translação (Mt):")
print("Matriz de Translação (Mt):")
print(Mt)

print("\nPonto Original (P):")
print(P)

# print("\nCálculo: Mt multiplicado por P") mesma coisa

print("\nNovo Ponto Transladado (P'):")
print(P_linha)

print("IMPRIMINDO ELEMENTO POR ELEMENTO DA MATRIZ RESULTADO:")
for i in range(linhas_P_linha):
  for j in range(colunas_P_linha):
    Elemento = P_linha[i, j]
    print(f"Linha {i}, Coluna {j} -> Valor: {Elemento}")